name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: voice-thought-app/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./voice-thought-app
    
    - name: Run linter
      run: npm run lint
      working-directory: ./voice-thought-app
    
    - name: Run type check
      run: npm run typecheck
      working-directory: ./voice-thought-app
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      working-directory: ./voice-thought-app
    
    - name: Build application
      run: npm run build
      working-directory: ./voice-thought-app
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '18.x'
      with:
        directory: ./voice-thought-app/coverage
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false